// Generated by tools/gen_fpga_bringup.py. Keep the script and this file together.
// UART transcript: VV32-A0 ready\r\n, VV64-P0 ready\r\n, VV64-E0 ready\r\n.
`timescale 1ns/1ps

module vv32_bringup_rom (
  input  logic [63:0] addr_i,
  output logic [31:0] data_o
);
  always_comb begin
    data_o = 32'h0000_0000;
    case (addr_i[9:2])
      8'd0: data_o = 32'h08200000; // movi r1, 0
      8'd1: data_o = 32'h0c400002; // lui r2, 2
      8'd2: data_o = 32'h81411003; // croot c10, r1, r2, rw
      8'd3: data_o = 32'hbc000000; // vlock
      8'd4: data_o = 32'h0c800001; // lui r4, 1
      8'd5: data_o = 32'h8d6a2000; // cinc c11, c10, r4
      8'd6: data_o = 32'h08600056; // movi r3, 0x56
      8'd7: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd8: data_o = 32'h08600056; // movi r3, 0x56
      8'd9: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd10: data_o = 32'h08600033; // movi r3, 0x33
      8'd11: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd12: data_o = 32'h08600032; // movi r3, 0x32
      8'd13: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd14: data_o = 32'h0860002d; // movi r3, 0x2d
      8'd15: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd16: data_o = 32'h08600041; // movi r3, 0x41
      8'd17: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd18: data_o = 32'h08600030; // movi r3, 0x30
      8'd19: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd20: data_o = 32'h08600020; // movi r3, 0x20
      8'd21: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd22: data_o = 32'h08600072; // movi r3, 0x72
      8'd23: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd24: data_o = 32'h08600065; // movi r3, 0x65
      8'd25: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd26: data_o = 32'h08600061; // movi r3, 0x61
      8'd27: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd28: data_o = 32'h08600064; // movi r3, 0x64
      8'd29: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd30: data_o = 32'h08600079; // movi r3, 0x79
      8'd31: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd32: data_o = 32'h0860000d; // movi r3, 0x0d
      8'd33: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd34: data_o = 32'h0860000a; // movi r3, 0x0a
      8'd35: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd36: data_o = 32'h08a00010; // movi r5, 0x10
      8'd37: data_o = 32'h8d8b2800; // cinc c12, c11, r5
      8'd38: data_o = 32'h08c00032; // movi r6, 0x32
      8'd39: data_o = 32'hb4cc0000; // cstw r6, c12, 0
      8'd40: data_o = 32'h08a00028; // movi r5, 0x28
      8'd41: data_o = 32'h8d8b2800; // cinc c12, c11, r5
      8'd42: data_o = 32'h08c00032; // movi r6, 0x32
      8'd43: data_o = 32'hb4cc0000; // cstw r6, c12, 0
      8'd44: data_o = 32'h60000000; // halt
      default: ;
    endcase
  end
endmodule

module vv64_p_bringup_rom (
  input  logic [63:0] addr_i,
  output logic [31:0] data_o
);
  always_comb begin
    data_o = 32'h0000_0000;
    case (addr_i[9:2])
      8'd0: data_o = 32'h08200000; // movi r1, 0
      8'd1: data_o = 32'h0c400002; // lui r2, 2
      8'd2: data_o = 32'h81411003; // croot c10, r1, r2, rw
      8'd3: data_o = 32'hbc000000; // vlock
      8'd4: data_o = 32'h0c800001; // lui r4, 1
      8'd5: data_o = 32'h8d6a2000; // cinc c11, c10, r4
      8'd6: data_o = 32'h08600056; // movi r3, 0x56
      8'd7: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd8: data_o = 32'h08600056; // movi r3, 0x56
      8'd9: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd10: data_o = 32'h08600036; // movi r3, 0x36
      8'd11: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd12: data_o = 32'h08600034; // movi r3, 0x34
      8'd13: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd14: data_o = 32'h0860002d; // movi r3, 0x2d
      8'd15: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd16: data_o = 32'h08600050; // movi r3, 0x50
      8'd17: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd18: data_o = 32'h08600030; // movi r3, 0x30
      8'd19: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd20: data_o = 32'h08600020; // movi r3, 0x20
      8'd21: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd22: data_o = 32'h08600072; // movi r3, 0x72
      8'd23: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd24: data_o = 32'h08600065; // movi r3, 0x65
      8'd25: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd26: data_o = 32'h08600061; // movi r3, 0x61
      8'd27: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd28: data_o = 32'h08600064; // movi r3, 0x64
      8'd29: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd30: data_o = 32'h08600079; // movi r3, 0x79
      8'd31: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd32: data_o = 32'h0860000d; // movi r3, 0x0d
      8'd33: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd34: data_o = 32'h0860000a; // movi r3, 0x0a
      8'd35: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd36: data_o = 32'h08a00018; // movi r5, 0x18
      8'd37: data_o = 32'h8d8b2800; // cinc c12, c11, r5
      8'd38: data_o = 32'h08c00050; // movi r6, 0x50
      8'd39: data_o = 32'hb4cc0000; // cstw r6, c12, 0
      8'd40: data_o = 32'h08a00028; // movi r5, 0x28
      8'd41: data_o = 32'h8d8b2800; // cinc c12, c11, r5
      8'd42: data_o = 32'h08c00050; // movi r6, 0x50
      8'd43: data_o = 32'hb4cc0000; // cstw r6, c12, 0
      8'd44: data_o = 32'h60000000; // halt
      default: ;
    endcase
  end
endmodule

module vv64_e_bringup_rom (
  input  logic [63:0] addr_i,
  output logic [31:0] data_o
);
  always_comb begin
    data_o = 32'h0000_0000;
    case (addr_i[9:2])
      8'd0: data_o = 32'h08200000; // movi r1, 0
      8'd1: data_o = 32'h0c400002; // lui r2, 2
      8'd2: data_o = 32'h81411003; // croot c10, r1, r2, rw
      8'd3: data_o = 32'hbc000000; // vlock
      8'd4: data_o = 32'h0c800001; // lui r4, 1
      8'd5: data_o = 32'h8d6a2000; // cinc c11, c10, r4
      8'd6: data_o = 32'h08600056; // movi r3, 0x56
      8'd7: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd8: data_o = 32'h08600056; // movi r3, 0x56
      8'd9: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd10: data_o = 32'h08600036; // movi r3, 0x36
      8'd11: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd12: data_o = 32'h08600034; // movi r3, 0x34
      8'd13: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd14: data_o = 32'h0860002d; // movi r3, 0x2d
      8'd15: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd16: data_o = 32'h08600045; // movi r3, 0x45
      8'd17: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd18: data_o = 32'h08600030; // movi r3, 0x30
      8'd19: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd20: data_o = 32'h08600020; // movi r3, 0x20
      8'd21: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd22: data_o = 32'h08600072; // movi r3, 0x72
      8'd23: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd24: data_o = 32'h08600065; // movi r3, 0x65
      8'd25: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd26: data_o = 32'h08600061; // movi r3, 0x61
      8'd27: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd28: data_o = 32'h08600064; // movi r3, 0x64
      8'd29: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd30: data_o = 32'h08600079; // movi r3, 0x79
      8'd31: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd32: data_o = 32'h0860000d; // movi r3, 0x0d
      8'd33: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd34: data_o = 32'h0860000a; // movi r3, 0x0a
      8'd35: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd36: data_o = 32'h08a00020; // movi r5, 0x20
      8'd37: data_o = 32'h8d8b2800; // cinc c12, c11, r5
      8'd38: data_o = 32'h08c00045; // movi r6, 0x45
      8'd39: data_o = 32'hb4cc0000; // cstw r6, c12, 0
      8'd40: data_o = 32'h08a00028; // movi r5, 0x28
      8'd41: data_o = 32'h8d8b2800; // cinc c12, c11, r5
      8'd42: data_o = 32'h08c00045; // movi r6, 0x45
      8'd43: data_o = 32'hb4cc0000; // cstw r6, c12, 0
      8'd44: data_o = 32'h60000000; // halt
      default: ;
    endcase
  end
endmodule

module vv64_bringup_rom (
  input  logic [63:0] addr_i,
  output logic [31:0] data_o
);
  always_comb begin
    data_o = 32'h0000_0000;
    case (addr_i[9:2])
      8'd0: data_o = 32'h08200000; // movi r1, 0
      8'd1: data_o = 32'h0c400002; // lui r2, 2
      8'd2: data_o = 32'h81411003; // croot c10, r1, r2, rw
      8'd3: data_o = 32'hbc000000; // vlock
      8'd4: data_o = 32'h0c800001; // lui r4, 1
      8'd5: data_o = 32'h8d6a2000; // cinc c11, c10, r4
      8'd6: data_o = 32'h08600056; // movi r3, 0x56
      8'd7: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd8: data_o = 32'h08600056; // movi r3, 0x56
      8'd9: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd10: data_o = 32'h08600036; // movi r3, 0x36
      8'd11: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd12: data_o = 32'h08600034; // movi r3, 0x34
      8'd13: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd14: data_o = 32'h0860002d; // movi r3, 0x2d
      8'd15: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd16: data_o = 32'h08600041; // movi r3, 0x41
      8'd17: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd18: data_o = 32'h08600030; // movi r3, 0x30
      8'd19: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd20: data_o = 32'h08600020; // movi r3, 0x20
      8'd21: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd22: data_o = 32'h08600072; // movi r3, 0x72
      8'd23: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd24: data_o = 32'h08600065; // movi r3, 0x65
      8'd25: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd26: data_o = 32'h08600061; // movi r3, 0x61
      8'd27: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd28: data_o = 32'h08600064; // movi r3, 0x64
      8'd29: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd30: data_o = 32'h08600079; // movi r3, 0x79
      8'd31: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd32: data_o = 32'h0860000d; // movi r3, 0x0d
      8'd33: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd34: data_o = 32'h0860000a; // movi r3, 0x0a
      8'd35: data_o = 32'hac6b0000; // cstb r3, c11, 0
      8'd36: data_o = 32'h08a00018; // movi r5, 0x18
      8'd37: data_o = 32'h8d8b2800; // cinc c12, c11, r5
      8'd38: data_o = 32'h08c00064; // movi r6, 0x64
      8'd39: data_o = 32'hb4cc0000; // cstw r6, c12, 0
      8'd40: data_o = 32'h08a00028; // movi r5, 0x28
      8'd41: data_o = 32'h8d8b2800; // cinc c12, c11, r5
      8'd42: data_o = 32'h08c00064; // movi r6, 0x64
      8'd43: data_o = 32'hb4cc0000; // cstw r6, c12, 0
      8'd44: data_o = 32'h60000000; // halt
      default: ;
    endcase
  end
endmodule
