#!/usr/bin/env python3
"""Regenerate the fixed ROM used by the Tang 138K bring-up image."""

from __future__ import annotations

from pathlib import Path

OP = {
    "MOVI": 0x02,
    "LUI": 0x03,
    "HALT": 0x18,
    "CROOT": 0x20,
    "CINC": 0x23,
    "CSTB": 0x2B,
    "CSTW": 0x2D,
    "VLOCK": 0x2F,
}

BootImage = tuple[str, str, int, int]

IMAGES: tuple[BootImage, ...] = (
    ("vv32_bringup_rom", "VV32-A0 ready\r\n", 0x10, 0x32),
    ("vv64_p_bringup_rom", "VV64-P0 ready\r\n", 0x18, 0x50),
    ("vv64_e_bringup_rom", "VV64-E0 ready\r\n", 0x20, 0x45),
)

LEGACY_IMAGE: BootImage = ("vv64_bringup_rom", "VV64-A0 ready\r\n", 0x18, 0x64)


def encode_r(op: str, rd: int, rs1: int, rs2: int, aux: int = 0) -> int:
    return (OP[op] << 26) | (rd << 21) | (rs1 << 16) | (rs2 << 11) | (aux & 0x7FF)


def encode_i(op: str, rd: int, rs1: int, immediate: int) -> int:
    return (OP[op] << 26) | (rd << 21) | (rs1 << 16) | (immediate & 0xFFFF)


def encode_none(op: str) -> int:
    return OP[op] << 26


def program(image: BootImage) -> list[tuple[int, str]]:
    _, message, mailbox_offset, marker = image
    words: list[tuple[int, str]] = []

    def emit(word: int, note: str) -> None:
        words.append((word & 0xFFFF_FFFF, note))

    emit(encode_i("MOVI", 1, 0, 0), "movi r1, 0")
    emit(encode_i("LUI", 2, 0, 2), "lui r2, 2")
    emit(encode_r("CROOT", 10, 1, 2, 3), "croot c10, r1, r2, rw")
    emit(encode_none("VLOCK"), "vlock")
    emit(encode_i("LUI", 4, 0, 1), "lui r4, 1")
    emit(encode_r("CINC", 11, 10, 4), "cinc c11, c10, r4")

    for byte in message.encode("ascii"):
        emit(encode_i("MOVI", 3, 0, byte), f"movi r3, 0x{byte:02x}")
        emit(encode_i("CSTB", 3, 11, 0), "cstb r3, c11, 0")

    emit(encode_i("MOVI", 5, 0, mailbox_offset), f"movi r5, 0x{mailbox_offset:02x}")
    emit(encode_r("CINC", 12, 11, 5), "cinc c12, c11, r5")
    emit(encode_i("MOVI", 6, 0, marker), f"movi r6, 0x{marker:02x}")
    emit(encode_i("CSTW", 6, 12, 0), "cstw r6, c12, 0")
    emit(encode_i("MOVI", 5, 0, 0x28), "movi r5, 0x28")
    emit(encode_r("CINC", 12, 11, 5), "cinc c12, c11, r5")
    emit(encode_i("MOVI", 6, 0, marker), f"movi r6, 0x{marker:02x}")
    emit(encode_i("CSTW", 6, 12, 0), "cstw r6, c12, 0")
    emit(encode_none("HALT"), "halt")
    return words


def render_module(image: BootImage) -> list[str]:
    module_name, _, _, _ = image
    lines = [
        f"module {module_name} (",
        "  input  logic [63:0] addr_i,",
        "  output logic [31:0] data_o",
        ");",
        "  always_comb begin",
        "    data_o = 32'h0000_0000;",
        "    case (addr_i[9:2])",
    ]
    lines.extend(
        f"      8'd{index}: data_o = 32'h{word:08x}; // {note}"
        for index, (word, note) in enumerate(program(image))
    )
    lines.extend(["      default: ;", "    endcase", "  end", "endmodule", ""])
    return lines


def render() -> str:
    lines = [
        "// Generated by tools/gen_fpga_bringup.py. Keep the script and this file together.",
        "// UART transcript: VV32-A0 ready\\r\\n, VV64-P0 ready\\r\\n, VV64-E0 ready\\r\\n.",
        "`timescale 1ns/1ps",
        "",
    ]
    for image in IMAGES:
        lines.extend(render_module(image))
    # Keep the old two-core testbench useful while the board projects use P0/E0.
    lines.extend(render_module(LEGACY_IMAGE))
    return "\n".join(lines)


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    output = root / "rtl" / "boot" / "vv_bringup_rom.sv"
    output.write_text(render(), encoding="utf-8")


if __name__ == "__main__":
    main()
